In [ ]:
# we use factorization in multible linear regression to minimizae speed and memory and also its happend as parallel so its very useful


In [3]:
import numpy as np

In [4]:
a=np.zeros(5)

In [5]:
a

array([0., 0., 0., 0., 0.])

In [6]:
np.random.rand(5)
# بتاخد الحجم علطول

array([0.45958904, 0.01322496, 0.88284841, 0.51758584, 0.31988102])

In [7]:
np.random.random_sample((5))
# بتاخد الحاجه ك tuple

array([0.78740711, 0.31260243, 0.86737791, 0.86154065, 0.18020467])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
a=np.array([1,2,3,4,5])
print(a.shape[0])
print(a.dtype)

5
int64


In [10]:
a=np.arange(10)
print(a)
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [11]:
# a[start:end:steps]
print(a[:])
print(a[1:])
print(a[:3])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 1 2]


In [12]:
a=np.array([1,2,3])
print(a)
b=-a
print(b)
b=np.sum(a)
print(b)
b=a*2
print(b)
print(a.mean())

[1 2 3]
[-1 -2 -3]
6
[2 4 6]
2.0


In [ ]:
# لازم فالجمع والطرح يبقي عندي ساعتها نفس shape

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a@b)
print(np.dot(a,b))

32
32


In [15]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [18]:
a=np.arange(6).reshape(-1,2)
print(a.shape)
print(a[2,0])

(3, 2)
4


In [34]:
a=np.arange(20).reshape(-1,10)
print(a.shape)
print(a[0,2:7:1])
print(a[:,2:7 :1])
print(a[1:])
print(a[:,:])
print(a[[0,1],[1,8]])

(2, 10)
[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
[[10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 1 18]
